apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hz2ir6nag-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hz2ir6nag-nodejs 
  name: hz2ir6nag-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hz2ir6nag-nodejs 
